src/Entity/Diagnostic.php
<?php

namespace App\Entity;

use App\Repository\DiagnosticRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Velo;
use App\Entity\Utilisateur;
use App\Entity\DiagnosticType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: DiagnosticRepository::class)]
class Diagnostic
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column]
    private ?int $id_velo = null;

    #[ORM\Column]
    private ?int $id_user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_diagnostic = null;

    #[ORM\Column(nullable: true)]
    private ?int $cout_reparation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $conclusion = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdDiagnostic(): ?int
    {
        return $this->id;
    }

    public function setIdDiagnostic(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getIdVelo(): ?int
    {
        return $this->id_velo;
    }

    public function setIdVelo(int $id_velo): static
    {
        $this->id_velo = $id_velo;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDateDiagnostic(): ?\DateTimeInterface
    {
        return $this->date_diagnostic;
    }

    public function setDateDiagnostic(\DateTimeInterface $date_diagnostic): static
    {
        $this->date_diagnostic = $date_diagnostic;

        return $this;
    }

    public function getCoutReparation(): ?int
    {
        return $this->cout_reparation;
    }

    public function setCoutReparation(?int $cout_reparation): static
    {
        $this->cout_reparation = $cout_reparation;

        return $this;
    }

    public function getConclusion(): ?string
    {
        return $this->conclusion;
    }

    public function setConclusion(?string $conclusion): static
    {
        $this->conclusion = $conclusion;

        return $this;
    }

    #[ORM\ManyToOne(targetEntity: Velo::class)]
    #[ORM\JoinColumn(name: "id_velo", referencedColumnName: "id")]

    private ?Velo $velo;


    #[ORM\ManyToOne(targetEntity: Utilisateur::class)]
    #[ORM\JoinColumn(name: "id_user", referencedColumnName: "id")]
    private ?Utilisateur $utilisateur;

    #[ORM\OneToMany(targetEntity: DiagnosticElement::class, mappedBy: 'diagnostic', cascade: ['persist', 'remove'])]
    private Collection $diagnosticElements;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'id')]
    #[ORM\JoinColumn(nullable: false)]
    private ?DiagnosticType $diagnosticType = null;

    #[ORM\ManyToOne(inversedBy: 'diagnostics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $Lieu_id = null;

    #[ORM\ManyToOne(inversedBy: 'diagnostics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?DiagnostictypeLieutype $Diagnostictype_LieuType_id = null;

    public function __construct()
    {
        $this->diagnosticElements = new ArrayCollection();
    }

    public function getDiagnosticElements(): Collection
    {
        return $this->diagnosticElements;
    }

     public function getDiagnosticType(): ?DiagnosticType
    {
        return $this->diagnosticType;
    }

    public function setDiagnosticType(?DiagnosticType $diagnosticType): static
    {
        $this->diagnosticType = $diagnosticType;

        return $this;
    }


    public function addDiagnosticElement(DiagnosticElement $diagnosticElement): self
    {
        if (!$this->diagnosticElements->contains($diagnosticElement)) {
            $this->diagnosticElements[] = $diagnosticElement;
            $diagnosticElement->setDiagnostic($this);
        }

        return $this;
    }

    public function removeDiagnosticElement(DiagnosticElement $diagnosticElement): self
    {
        if ($this->diagnosticElements->removeElement($diagnosticElement)) {
            // Set the owning side to null (unless already changed)
            if ($diagnosticElement->getDiagnostic() === $this) {
                $diagnosticElement->setDiagnostic(null);
            }
        }

        return $this;
    }


    public function getVelo(): ?Velo
    {
    return $this->velo;
    }

    public function setVelo(?Velo $velo): static
    {
    $this->velo = $velo;
    return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
    return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): static
    {
    $this->utilisateur = $utilisateur;

    return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getLieuId(): ?Lieu
    {
        return $this->Lieu_id;
    }

    public function setLieuId(?Lieu $Lieu_id): static
    {
        $this->Lieu_id = $Lieu_id;

        return $this;
    }

    public function getDiagnostictypeLieuTypeId(): ?DiagnostictypeLieutype
    {
        return $this->Diagnostictype_LieuType_id;
    }

    public function setDiagnostictypeLieuTypeId(?DiagnostictypeLieutype $Diagnostictype_LieuType_id): static
    {
        $this->Diagnostictype_LieuType_id = $Diagnostictype_LieuType_id;

        return $this;
    }


    }

src/Entity/Proprietaire.php
<?php
namespace App\Entity;

use App\Repository\ProprietaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProprietaireRepository::class)]
class Proprietaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_proprio = null;

    #[ORM\Column(nullable: true)]
    private ?string $telephone = null; 

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $statut = null;

    #[ORM\OneToMany(mappedBy: 'proprietaire', targetEntity: Velo::class)]
    private Collection $velos;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_de_naissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    public function __construct()
    {
        $this->velos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProprio(): ?string
    {
        return $this->nom_proprio;
    }

    public function setNomProprio(string $nom_proprio): self
    {
        $this->nom_proprio = $nom_proprio;
        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }


    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;
        return $this;
    }
    public function addVelo(Velo $velo): self
    {
        if (!$this->velos->contains($velo)) {
            $this->velos[] = $velo;
            $velo->setProprietaire($this);
        }
        return $this;
    }

    public function removeVelo(Velo $velo): self
    {
        if ($this->velos->removeElement($velo)) {
            if ($velo->getProprietaire() === $this) {
                $velo->setProprietaire(null);
            }
        }
        return $this;
    }

    // Assurez-vous que les champs pour displayName existent ou ajustez la méthode
    public function displayName(): string
    {
        return $this->nom_proprio; // Simplifiez si vous avez seulement un nom
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(?\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Entity/Velo.php
<?php

namespace App\Entity;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\VeloRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Entity\Diagnostic; // Import de l'entité Diagnostic si ce n'est pas déjà fait
#[ORM\Entity(repositoryClass: VeloRepository::class)]
class Velo
{

    public function removeDiagnostic(Diagnostic $diagnostic): self
    {
        if ($this->diagnostics->removeElement($diagnostic)) {
            // set the owning side to null (unless already changed)
            if ($diagnostic->getVelo() === $this) {
                $diagnostic->setVelo(null);
            }
        }

        return $this;
    }


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_de_serie = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true, unique: true)]
    private ?string $bicycode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ref_recyclerie = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $public = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $couleur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poids = null;

    #[ORM\Column(length: 255)]
    private ?string $taille_roues = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $taille_cadre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url_photo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_de_enregistrement = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_de_vente = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $emplacement = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $commentaire = null;
//
//     #[ORM\ManyToOne(inversedBy: 'proprietaire')]
//     #[ORM\JoinColumn(nullable: false)]
//     private ?Proprietaire $proprietaire = null;

#[ORM\ManyToOne(inversedBy: 'velos')]
#[ORM\JoinColumn(nullable: false)]
private ?Proprietaire $proprietaire = null;

#[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
private ?\DateTimeInterface $date_destruction = null;


 #[ORM\Column(type: "string", length: 255, nullable: true)]
            private ?string $origine = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $model = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroDeSerie(): ?string
    {
        return $this->numero_de_serie;
    }

    public function setNumeroDeSerie(string $numero_de_serie): static
    {
        $this->numero_de_serie = $numero_de_serie;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }


    public function getBicycode(): ?string
    {
        return $this->bicycode;
    }

    public function setBicycode(?string $bicycode): self
    {
        $this->bicycode = $bicycode;
        return $this;
    }





    public function getRefRecyclerie(): ?string
    {
        return $this->ref_recyclerie;
    }

    public function setRefRecyclerie(?string $ref_recyclerie): static
    {
        $this->ref_recyclerie = $ref_recyclerie;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): static
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getPoids(): ?string
    {
        return $this->poids;
    }

    public function setPoids(?string $poids): static
    {
        $this->poids = $poids;

        return $this;
    }


    public function getTailleRoues(): ?string
    {
        return $this->taille_roues;
    }

    public function setTailleRoues(string $taille_roues): static
    {
        $this->taille_roues = $taille_roues;

        return $this;
    }
    public function getTailleCadre(): ?string
    {
        return $this->taille_cadre;
    }

    public function setTailleCadre(?string $taille_cadre): self
    {
        $this->taille_cadre = $taille_cadre;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(string $url_photo): static
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getDateDeEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_de_enregistrement;
    }

    public function setDateDeEnregistrement(\DateTimeInterface $date_de_enregistrement): static
    {
        $this->date_de_enregistrement = $date_de_enregistrement;

        return $this;
    }


    public function getDateDeVente(): ?\DateTimeInterface
    {
        return $this->date_de_vente;
    }


    public function setDateDeVente($date_de_vente): self
    {
        if (is_string($date_de_vente)) {
            try {
                $date_de_vente = new \DateTime($date_de_vente);
            } catch (\Exception $e) {
                throw new \InvalidArgumentException("Date de vente invalide : " . $e->getMessage());
            }
        }
        $this->date_de_vente = $date_de_vente;
        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getEmplacement(): ?string
    {
        return $this->emplacement;
    }

    public function setEmplacement(string $emplacement): static
    {
        $this->emplacement = $emplacement;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getProprietaire(): ?Proprietaire
    {
        return $this->proprietaire;
    }

    public function setProprietaire(?Proprietaire $proprietaire): static
    {
        $this->proprietaire = $proprietaire;

        return $this;
    }

    public function getDateDestruction(): ?\DateTimeInterface
    {
        return $this->date_destruction;
    }

    public function setDateDestruction($date_destruction): self
    {
        if (is_string($date_destruction)) {
            $this->date_destruction = new \DateTime($date_destruction);
        } else {
            $this->date_destruction = $date_destruction;
        }
        return $this;
    }

    public function getPublic(): ?string
    {
        return $this->public;
    }

    public function setPublic(?string $public): static
    {
        $this->public = $public;

        return $this;
    }

 public function getOrigine(): ?string
                 {
                     return $this->origine;
                 }

        public function setOrigine(?string $origine): self
        {
            $this->origine = $origine;
            return $this;
        }

        public function getModel(): ?string
        {
            return $this->model;
        }

        public function setModel(?string $model): static
        {
            $this->model = $model;

            return $this;
        }

}

templates/diagnostic_en_cour/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        /* Animation Slide-In */
        @keyframes slideIn {
            from {
                transform: translateX(100%);
            }
            to {
                transform: translateX(0);
            }
        }

        /* Animation Slide-Out */
        @keyframes slideOut {
            from {
                transform: translateX(0);
            }
            to {
                transform: translateX(100%);
            }
        }

        /* Classe d'animation */
        .slide-in {
            animation: slideIn 0.5s ease-out forwards;
        }

        .slide-out {
            animation: slideOut 0.5s ease-in forwards;
        }

        @media screen and (max-width: 500px) {
            .logo-footer {
                display: block;
                position: fixed;
                bottom: 10px;
                left: 50%;
                transform: translateX(-50%);
            }

            .table-container {
                overflow-x: auto;
                -webkit-overflow-scrolling: touch;
            }

            .table {
                width: 100%;
            }
        }

        @media screen and (min-width: 501px) and (max-width: 900px) {
            .table-container {
                overflow-x: auto;
                -webkit-overflow-scrolling: touch;
            }

            .table {
                width: 100%;
            }

            .logo-footer {
                display: none;
            }
        }

        @media screen and (min-width: 901px) {
            .table-container {
                overflow-x: visible;
            }

            .table {
                width: auto;
                min-width: 900px;
            }

            .logo-footer {
                display: none;
            }
        }
    </style>
    <body class="flex flex-col min-h-screen">

        {% for message in app.flashes('success') %}
            <div class="fixed top-5 right-0 z-50 bg-white border border-gray-200 rounded-lg shadow-lg p-4 flex items-center gap-3 slide-in" id="flash-message">
                <div class="text-green-500">
                    <i class="bi bi-check-circle-fill text-green-500 text-xl"></i>
                </div>
                <div>
                    <p class="text-sm font-semibold text-gray-800">{{ message }}</p>
                </div>
                <button
                    type="button"
                    class="text-gray-400 hover:bg-gray-200 hover:text-gray-900 rounded-lg p-1.5 ml-auto inline-flex items-center"
                    onclick="hideFlashMessage()"
                >
                    <i class="bi bi-x-lg"></i>
                </button>
            </div>
        {% endfor %}

        <header class="flex relative w-full justify-between">
            <div id="headerLogoTissebands">
                <img src="{{ asset('images/EBNtrans.png') }}" alt="EBN Logo" class="size-40">
            </div>
            <div id="headerLogoCite">
                <img src="{{ asset('images/nouveau log 1.png') }}" alt="LCDRLR Logo">
            </div>
        </header>

        <main class="flex-1 p-4">
            <div class="container mx-auto">

                <div class="container mx-auto mb-4 px-4 sm:px-6 lg:px-8">
                    <h1 class="text-2xl font-bold text-black text-center">Créer/Continuer Diagnostic</h1>
                    <p class="text-gray-700 font-semibold text-center">{{lieu.nomType}} {{lieu.nom}} à {{lieu.ville}}</p>
                </div>

                <nav class="w-full py-3 px-4 container mx-auto flex flex-col sm:flex-row justify-center sm:items-center space-y-2 sm:space-y-0 sm:space-x-4 mb-4">
                    <ol class="breadcrumb flex flex-wrap items-center space-x-2 sm:space-x-4">
                        <li class="breadcrumb-item font-bold">
                            <a href="{{ path('app_accueil') }}" class="text-blue-500 hover:text-blue-600 font-bold flex items-center">
                                <i class="fas fa-home mr-2"></i>
                            </a>
                        </li>
                        <li><i class="fas fa-angle-right text-gray-400"></i></li>
                        <li class="breadcrumb-item text-black font-bold flex items-center">
                            <i class="fas fa-tasks mr-2"></i> Diagnostic
                        </li>
                        <li><i class="fas fa-angle-right text-gray-400"></i></li>
                        <li class="breadcrumb-item font-bold">
                            <a href="{{ path('app_accueil', { 'modal': 'open' }) }}" class="text-blue-500 hover:text-blue-600 font-bold flex items-center hover:underline">
                                <i class="fas fa-map-marker-alt mr-2"></i> Lieu
                            </a>
                        </li>
                        <li><i class="fas fa-angle-right text-gray-400"></i></li>
                        <li class="breadcrumb-item font-bold">
                            Créer/Continuer  diagnostic
                        </li>
                    </ol>
                </nav>


                <div class="flex justify-center mb-4">
                    <a href="/velo/all" class="bg-teal-500 hover:bg-green-400 text-white rounded-lg px-4 py-2 text-sm shadow transition-colors duration-200 w-auto inline-flex items-center justify-center">
                        <i class="bi bi-plus text-lg mr-1"></i>
                        Créer un diagnostic
                    </a>

            </div>
            <h1 class="text-3xl font-bold text-center text-black mb-6">Diagnostics en cours</h1>
            <div class="table-container max-w-full">
                <table class="table-auto max-w-6xl mx-auto text-center border-2 border-gray-300 rounded-lg border-separate">
                    <thead class="text-lg bg-gray-200">
                    <tr class=" text-lg text-black">

                        <th class="px-2 py-2 whitespace-nowrap">Numéro de série</th>
                        <th class="px-2 py-2">Bicycode</th>
                        <th class="px-2 py-2 whitespace-nowrap">Reference Recyclerie</th>
                        <th class="px-2 py-2">Marque</th>
                        <th class="px-2 py-2">Type</th>
                        <th class="px-2 py-2">Couleur</th>
                        <th class="px-2 py-2 whitespace-nowrap">Date du diagnostic </th>
                        <th class="px-2 py-2">Propriétaire</th>
                        <th class="px-2 py-2"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in filteredDiagnostics %}
                        <tr class="border">
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.numeroSerie }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.bicycode }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.refRecyclerie }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.marque }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap ">{{ item.veloDetails.type }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.couleur }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.diagnostic.dateDiagnostic|date('d/m/Y H:i') }}</td>
                            <td class="px-4 py-2 border-r border-b whitespace-nowrap">{{ item.veloDetails.proprio.nomProprio }}</td>
                            <td class="px-4 py-2 ">
                                <a href="{{ path('reprendre_Multidiagnostic', {'id': item.diagnostic.id}) }}" class="py-2 px-4 bg-teal-500 text-white font-semibold rounded hover:bg-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-opacity-50">
                                    Continuer
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            </div>

        </main>

        <footer class="w-full">
            <div id="bottom-logo" class="flex justify-center items-center py-6">
                <img src="{{ asset('images/nouveau log 1.png') }}" alt="Logo de l'entreprise" >
            </div>
        </footer>
    </body>

    <script>
        function hideFlashMessage() {
            const flashMessage = document.getElementById('flash-message');
            if (flashMessage) {
                flashMessage.classList.remove('slide-in');
                flashMessage.classList.add('slide-out');

                setTimeout(() => {
                    flashMessage.remove();
                }, 500);
            }
        }

        setTimeout(() => {
            hideFlashMessage();
        }, 5000);
    </script>
{% endblock %}