src/Entity/TypeLieu.php
<?php

namespace App\Entity;

use App\Repository\TypeLieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TypeLieuRepository::class)]
class TypeLieu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_type_lieu = null;

    #[ORM\Column]
    private ?bool $actif = null;

    /**
     * @var Collection<int, Lieu>
     */
    #[ORM\OneToMany(targetEntity: Lieu::class, mappedBy: 'type_lieu_id')]
    private Collection $lieus;

    /**
     * @var Collection<int, DiagnostictypeLieutype>
     */
    #[ORM\OneToMany(targetEntity: DiagnostictypeLieutype::class, mappedBy: 'Lieu_type_id')]
    private Collection $diagnostictypeLieutypes;

    public function __construct()
    {
        $this->lieus = new ArrayCollection();
        $this->diagnostictypeLieutypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomTypeLieu(): ?string
    {
        return $this->nom_type_lieu;
    }

    public function setNomTypeLieu(string $nom_type_lieu): static
    {
        $this->nom_type_lieu = $nom_type_lieu;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): static
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * @return Collection<int, Lieu>
     */
    public function getLieus(): Collection
    {
        return $this->lieus;
    }

    public function addLieu(Lieu $lieu): static
    {
        if (!$this->lieus->contains($lieu)) {
            $this->lieus->add($lieu);
            $lieu->setTypeLieuId($this);
        }

        return $this;
    }

    public function removeLieu(Lieu $lieu): static
    {
        if ($this->lieus->removeElement($lieu)) {
            // set the owning side to null (unless already changed)
            if ($lieu->getTypeLieuId() === $this) {
                $lieu->setTypeLieuId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, DiagnostictypeLieutype>
     */
    public function getDiagnostictypeLieutypes(): Collection
    {
        return $this->diagnostictypeLieutypes;
    }

    public function addDiagnostictypeLieutype(DiagnostictypeLieutype $diagnostictypeLieutype): static
    {
        if (!$this->diagnostictypeLieutypes->contains($diagnostictypeLieutype)) {
            $this->diagnostictypeLieutypes->add($diagnostictypeLieutype);
            $diagnostictypeLieutype->setLieuTypeId($this);
        }

        return $this;
    }

    public function removeDiagnostictypeLieutype(DiagnostictypeLieutype $diagnostictypeLieutype): static
    {
        if ($this->diagnostictypeLieutypes->removeElement($diagnostictypeLieutype)) {
            // set the owning side to null (unless already changed)
            if ($diagnostictypeLieutype->getLieuTypeId() === $this) {
                $diagnostictypeLieutype->setLieuTypeId(null);
            }
        }

        return $this;
    }
}

src/Form/TypeLieuType.php
<?php

namespace App\Form;

use App\Entity\TypeLieu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeLieuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_type_lieu')
            ->add('actif')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TypeLieu::class,
        ]);
    }
}

src/Controller/TypeLieuController.php
<?php

namespace App\Controller;

use App\Entity\TypeLieu;
use App\Form\TypeLieuType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class TypeLieuController extends AbstractController
{
    #[Route('/type/lieu', name: 'app_type_lieu_liste')]
    public function index(EntityManagerInterface $entityManager, Request $request): Response
    {
        $status = $request->query->get('status');
        $typesLieu = [];

        if ($status === '1') {
            $typesLieu = $entityManager->getRepository(TypeLieu::class)->findBy(['actif' => true]);
        } elseif ($status === '0') {
            $typesLieu = $entityManager->getRepository(TypeLieu::class)->findBy(['actif' => false]);
        } else {
            $typesLieu = $entityManager->getRepository(TypeLieu::class)->findAll();
        }

        return $this->render('type_lieu/liste.html.twig', [
            'typesLieu' => $typesLieu,
        ]);
    }

// Route pour changer le statut
    #[Route('/dashboard/typelieu/toggle/{id}', name: 'toggle_lieu_status', methods: ['POST'])]
    public function toggleStatus(int $id, EntityManagerInterface $entityManager): JsonResponse
    {
        $lieuType = $entityManager->getRepository(TypeLieu::class)->find($id);

        if (!$lieuType) {
            return new JsonResponse(['message' => 'Aucun type de lieu trouvé'], Response::HTTP_NOT_FOUND);
        }

        $lieuType->setActif(!$lieuType->isActif());
        $entityManager->flush();

        return new JsonResponse([
            'message' => 'Statut modifié avec succès',
            'newStatus' => $lieuType->isActif() ? 'Active' : 'Inactive'
        ]);
    }

    #[Route('/dashboard/typelieu/new/lieu/type', name: 'app_create_lieu_type')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $typeLieu = new TypeLieu();

        $form = $this->createForm(TypeLieuType::class, $typeLieu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $entityManager->persist($typeLieu);
                $entityManager->flush();
            
                $this->addFlash('success', 'Nouveau type de lieu enregistré avec succès !');
                return $this->redirectToRoute('app_type_lieu_liste');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Une erreur est survenue lors de l\'enregistrement, Veuillez réasseyer ultérieurement');
                return $this->redirectToRoute('app_type_lieu_liste');
            }
        }

        return $this->render('type_lieu/newTypeLieu.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/type_lieu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TypeLieuController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/home/vassal/Documents/Projets/Projet_UHA_5/velo/src/Controller/TypeLieuController.php</code></li>
        <li>Your template at <code>/home/vassal/Documents/Projets/Projet_UHA_5/velo/templates/type_lieu/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/type_lieu/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Types de lieu{% endblock title %}

{% block body %}
    <!--Notification en cas de réussite !-->
    {% for message in app.flashes('success') %}
        <div class="fixed top-5 right-0 z-50 bg-white border border-gray-200 rounded-lg shadow-lg p-4 flex items-center gap-3 slide-in" id="flash-message">
            <div class="text-green-500">
                <i class="bi bi-check-circle-fill text-green-500 text-xl"></i>
            </div>
            <div>
                <p class="text-sm font-semibold text-gray-800">{{ message }}</p>
            </div>
            <button
                type="button"
                class="text-gray-400 hover:bg-gray-200 hover:text-gray-900 rounded-lg p-1.5 ml-auto inline-flex items-center"
                onclick="hideFlashMessage()"
            >
                <i class="bi bi-x-lg"></i>
            </button>
        </div>
    {% endfor %}
    <!--Notification en cas d'erreur !-->
    {% for message in app.flashes('error') %}
        <div class="fixed top-5 right-0 z-50 bg-white border border-red-200 rounded-lg shadow-lg p-4 flex items-center gap-3 slide-in" id="flash-message">
            <div class="text-red-500">
                <i class="bi bi-x-circle-fill text-red-500 text-xl"></i>
            </div>
            <div>
                <p class="text-sm font-semibold text-gray-800">{{ message }}</p>
            </div>
            <button
                type="button"
                class="text-gray-400 hover:bg-gray-200 hover:text-gray-900 rounded-lg p-1.5 ml-auto inline-flex items-center"
                onclick="hideFlashMessage()"
            >
                <i class="bi bi-x-lg"></i>
            </button>
        </div>
    {% endfor %}


    <style>
    
        /* Animation Slide-In */
        @keyframes slideIn {
            from {
                transform: translateX(100%); 
            }
            to {
                transform: translateX(0);
            }
        }

        /* Animation Slide-Out */
        @keyframes slideOut {
            from {
                transform: translateX(0);
            }
            to {
                transform: translateX(100%);
            }
        }

        /* Classe d'animation */
        .slide-in {
            animation: slideIn 0.5s ease-out forwards;
        }

        .slide-out {
            animation: slideOut 0.5s ease-in forwards;
        }
        
    </style>
    <div class="container mx-auto mt-8">
        <h1 class="text-2xl font-bold mb-6 text-center">Types de lieu</h1>

        <div>
            <a href="{{ path('app_create_lieu_type') }}" class="button-style w-full hover:bg-green-400"><i class="bi bi-plus-circle mr-2"></i>Ajouter un type de lieu</a>
        </div>

        <!-- Form for filtering -->
        <form action="{{ path('app_type_lieu_liste') }}" method="get" class="mb-4">
            <label for="status" class="block text-sm font-medium text-gray-700">Filtrer par statut:</label>
            <select id="status" name="status" class="mt-1 block w-1/5 pl-5 pr-16 py-3 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" onchange="this.form.submit()">
                <option value="">Tous</option>
                <option value="1" {{ app.request.query.get('status') == '1' ? 'selected' : '' }}>Actif</option>
                <option value="0" {{ app.request.query.get('status') == '0' ? 'selected' : '' }}>Inactif</option>
            </select>
        </form>

        <!-- Table -->
        <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="py-3 px-6">Status</th>
                    <th scope="col" class="py-3 px-6">ID</th>
                    <th scope="col" class="py-3 px-6">Type de lieu</th>
                </tr>
                </thead>
                <tbody>
                {% for lieu in typesLieu %}
                    <tr class="bg-white border-b {{ lieu.actif ? 'bg-white' : 'bg-gray-300' }}">
                        <td class="py-4 px-6">
                            <label class="inline-flex items-center me-5 cursor-pointer">
                                <input type="checkbox" class="sr-only peer" {{ lieu.actif ? 'checked' : '' }}
                                       onclick="toggleLieuStatus({{ lieu.id }})">
                                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer dark:bg-gray-700 peer-focus:ring-4 peer-focus:ring-green-300 dark:peer-focus:ring-green-800 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
                                <span id="status-{{ lieu.id }}" class="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">{{ lieu.actif ? 'Actif' : 'Inactif' }}</span>
                            </label>
                        </td>
                        <td class="py-4 px-6">{{ lieu.id }}</td>
                        <td class="py-4 px-6">{{ lieu.nomTypeLieu }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="mt-6 flex justify-center">
            <a href="{{ path('app_dashboard') }}" class="button-style hover:bg-green-400"><i class="bi bi-box-arrow-left text-xl"></i> Retour au tableau de bord</a>
        </div>
 
        <!-- JavaScript -->
        <script>

            function hideFlashMessage() {
                const flashMessage = document.getElementById('flash-message');
                if (flashMessage) {
                    flashMessage.classList.remove('slide-in');
                    flashMessage.classList.add('slide-out');

                    setTimeout(() => {
                        flashMessage.remove();
                    }, 500); 
                }
            }
            
            setTimeout(() => {
                hideFlashMessage();
            }, 5000);

            function hideErrorNotification() {
                const errorNotification = document.getElementById('error-notification');
                if (errorNotification) {
                    errorNotification.classList.remove('slide-in');
                    errorNotification.classList.add('slide-out');

                    setTimeout(() => {
                        errorNotification.remove();
                    }, 500);
                }
            }

            setTimeout(() => {
                hideErrorNotification();
            }, 7000);

            function toggleLieuStatus(lieuId) {
                fetch(`{{ path('toggle_lieu_status', {'id': 0}) }}`.replace('/0', '/' + lieuId), {
                    method: 'POST',
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.message) {
                            const statusElement = document.getElementById(`status-${lieuId}`);
                            if (statusElement) {
                                statusElement.textContent = data.newStatus === 'Active' ? 'Actif' : 'Inactif';
                            }
                        }
                    })
                    .catch(error => {
                        console.error('Erreur :', error);
                        alert('Erreur', 'Une erreur s\'est produite lors de la mise à jour du statut.');
                    });
            }
        </script>

{% endblock %}

templates/type_lieu/newTypeLieu.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
        <div class="container max-w-lg text-center border bg-white shadow rounded-lg">


            {{ form_start(form) }}
            <h1 class="text-2xl font-bold my-4">Créer un nouveau type de lieu</h1>
            <div class="mb-3">
                <h3>Nom du type de lieu</h3>
                {{ form_widget(form.nom_type_lieu, {'attr': {'class': 'p-2 border border-gray-300 rounded'}}) }}
            </div>


            <div class="mt-4">
                <button type="submit" class="bg-teal-500 text-white py-2 px-4 rounded hover:bg-teal-600">Créer</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="mt-6 flex justify-center">
        <a href="{{ path('app_type_lieu_liste') }}" class="button-style hover:bg-green-400"><i class="bi bi-box-arrow-left text-xl"></i> Retour liste type des lieux</a>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('.toggle-category').forEach(button => {
                button.addEventListener('click', function () {
                    var categoryElements = this.closest('.category').querySelector('.category-elements');
                    categoryElements.style.display = categoryElements.style.display === 'none' ? 'block' : 'none';
                });
            });

            document.querySelectorAll('.select-all-checkbox').forEach(selectAllCheckbox => {
                selectAllCheckbox.addEventListener('change', function () {
                    var category = this.getAttribute('data-category');
                    var checkboxes = document.querySelectorAll(`.element-checkbox[data-category="${category}"]`);
                    checkboxes.forEach(checkbox => {
                        checkbox.checked = this.checked;
                    });
                });
            });

            document.querySelectorAll('.element-checkbox').forEach(checkbox => {
                checkbox.addEventListener('change', function () {
                    var category = this.getAttribute('data-category');
                    var allCheckboxes = document.querySelectorAll(`.element-checkbox[data-category="${category}"]`);
                    var selectAllCheckbox = document.querySelector(`.select-all-checkbox[data-category="${category}"]`);
                    var allChecked = Array.from(allCheckboxes).every(cb => cb.checked);
                    selectAllCheckbox.checked = allChecked;
                });
            });
        });
    </script>
{% endblock %}